=== padasio/padas-docs/v0.0.9/assets/config/PadasTaskSchema.json
{
  "$id": "https://padas.io/schemas/task",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "required": [
    "id",
    "name",
    "description",
    "function",
    "definition"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": ["number", "string"]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "definition": true,
    "function": {
      "type": "string",
      "enum": [
        "TIMESTAMP",
        "FILTER",
        "EXTRACT",
        "PARSE_CSV",
        "PARSE_KV",
        "PDL_EXPRESSION",
        "APPLY_RULES"
      ]
    }
  },
  "if": {"required": ["function"]},
  "then": {
    "anyOf": [
      {
        "properties": {
          "function": {"const": "TIMESTAMP"},
          "definition": {"$ref": "#/definitions/timestamp"}
        }
      },
      {
        "properties": {
          "function": {"const": "FILTER"},
          "definition": {"$ref": "#/definitions/filter"}
        }
      },
      {
        "properties": {
          "function": {"const": "EXTRACT"},
          "definition": {"$ref": "#/definitions/extract"}
        }
      },
      {
        "properties": {
          "function": {"const": "PARSE_CSV"},
          "definition": {"$ref": "#/definitions/parse_csv"}
        }
      },
      {
        "properties": {
          "function": {"const": "PARSE_KV"},
          "definition": {"$ref": "#/definitions/parse_kv"}
        }
      },
      {
        "properties": {
          "function": {"const": "PDL_EXPRESSION"},
          "definition": {"$ref": "#/definitions/pdl_expression"}
        }
      },
      {
        "properties": {
          "function": {"const": "APPLY_RULES"},
          "definition": {"$ref": "#/definitions/apply_rules"}
        }
      }
    ]
  },
  "definitions": {
    "timestamp": {
      "type": "object",
      "title": "TIMESTAMP",
      "required": [
        "field",
        "format"
      ],
      "properties": {
        "field": {
          "type": "string"
        },
        "format": {
          "type": "string"
        },
        "addNewField": {
          "type": "boolean",
          "default": true
        },
        "timeFieldName": {
          "type": "string",
          "default": "_time"
        }
      }
    },
    "filter": {
      "type": "object",
      "title": "FILTER",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "regex",
            "pdl"
          ]
        },
        "action": {
          "type": "string",
          "enum": [
            "keep",
            "drop"
          ],
          "default": "keep"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "extract": {
      "type": "object",
      "title": "EXTRACT",
      "required": [
        "regex"
      ],
      "properties": {
        "field": {
          "type": "string",
          "default": "_raw"
        },
        "regex": {
          "type": "string"
        },
        "keepRaw": {
          "type": "boolean",
          "default": true
        },
        "rawFieldName": {
          "type": "string",
          "default": "_raw"
        }
      }
    },
    "parse_csv": {
      "type": "object",
      "title": "PARSE_CSV",
      "required": [
        "fieldNames"
      ],
      "properties": {
        "fieldNames": {
          "type": "string"
        },
        "delimiter": {
          "type": "string",
          "default": ","
        },
        "keepRaw": {
          "type": "boolean",
          "default": true
        },
        "rawFieldName": {
          "type": "string",
          "default": "_raw"
        }
      }
    },
    "parse_kv": {
      "type": "object",
      "title": "PARSE_KV",
      "properties": {
        "delimiter": {
          "type": "string",
          "default": "="
        },
        "keepRaw": {
          "type": "boolean",
          "default": true
        },
        "rawFieldName": {
          "type": "string",
          "default": "_raw"
        }
      }
    },
    "pdl_expression": {
      "type": "object",
      "title": "PDL_EXPRESSION",
      "properties": {
        "pdl": {
          "type": "string"
        }
      }
    },
    "apply_rules": {
      "type": "object",
      "title": "APPLY_RULES",
      "required": ["rules"],
      "properties": {
        "rules": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "matchAll": {
          "type": "boolean",
          "default": true
        }
      }
    }
  }
}

=== padasio/padas-docs/v0.0.2/assets/config/PadasTasks_apply_rules_winlogbeat_sysmon.json
[
  {
    "id": 110,
    "name": "Endpoint:Rules",
    "description": "Endpoint rules",
    "function": "APPLY_RULES",
    "definition": {
      "datamodels": [
        {
          "condition": "event.code=\"1\"",
          "datamodel": "EndpointProcess",
          "matchAll": true
        },
        {
          "condition": "event.code=\"3\"",
          "datamodel": "EndpointListeningPort",
          "matchAll": true
        }
      ]
    }
  }
]

=== padasio/padas-docs/docs/assets/config/PadasQuickStartTasks.json
[
  {
    "id": 1,
    "name": "Test Eval",
    "description": "Map group id to name",
    "function": "PDL_EXPRESSION",
    "definition": {
      "pdl": "eval group_name=if(group_id=1,\"evil group\",\"some other group\")"
    }
  },
  {
    "id": 2,
    "name": "Test Rules",
    "description": "Apply rules for mydata",
    "function": "APPLY_RULES",
    "definition": {
      "rules" : ["test_rule_for_evil", "test_rule_for_failure"],
      "matchAll": true
    }
  }
]
